# Generated by Django 5.2.17 on 2026-10-08 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suscripciones', '0004_alter_suscripcion_fecha_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría.', max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Baja lógica.')),
                ('licorera', models.ForeignKey(db_column='licorera_id', help_text='Licorera dueña del registro; sostiene el aislamiento entre negocios.', on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='suscripciones.licorera')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la referencia («Aguardiente Antioqueño 750 ml»).', max_length=120)),
                ('presentacion', models.CharField(choices=[('media', 'Media'), ('botella', 'Botella'), ('litro', 'Litro'), ('garrafa', 'Garrafa'), ('unidad', 'Unidad')], help_text='Presentación comercial de la referencia.', max_length=10)),
                ('codigo_barras', models.CharField(blank=True, help_text='Código de barras; único dentro de la licorera si se registra.', max_length=50, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Precio de venta vigente. Vive separado del costo (RF-INV-11) y solo lo cambia el administrador; las ventas ya hechas conservan el suyo.', max_digits=12)),
                ('stock_minimo', models.PositiveIntegerField(default=0, help_text='Umbral de la alerta de existencias bajas (RF-INV-07).')),
                ('activo', models.BooleanField(default=True, help_text='Baja lógica (RF-INV-04): no aparece en el punto de venta, conserva historial.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó la referencia.')),
                ('categoria', models.ForeignKey(db_column='categoria_id', help_text='Categoría del producto.', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria')),
                ('licorera', models.ForeignKey(db_column='licorera_id', help_text='Licorera dueña del registro; sostiene el aislamiento entre negocios.', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='suscripciones.licorera')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('licorera', 'nombre'), name='categoria_unica_por_licorera'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_barras__isnull', False)), fields=('licorera', 'codigo_barras'), name='codigo_barras_unico_por_licorera'),
        ),
    ]
