# Generated by Django 5.2.17 on 2026-10-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('suscripciones', '0004_alter_suscripcion_fecha_fin'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='producto',
            name='codigo_barras_unico_por_licorera',
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('licorera', 'codigo_barras'), name='codigo_barras_unico_por_licorera'),
        ),
    ]
