# Generated by Django 5.2.17 on 2026-10-09 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_producto_codigo_barras_unico_por_licorera_and_more'),
        ('sedes', '0001_initial'),
        ('suscripciones', '0004_alter_suscripcion_fecha_fin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaMercancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(blank=True, help_text='Nombre del proveedor (texto libre en esta versión).', max_length=100, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la entrada.')),
                ('observacion', models.CharField(blank=True, help_text='Nota opcional (número de factura del proveedor, etc.).', max_length=255, null=True)),
                ('licorera', models.ForeignKey(db_column='licorera_id', help_text='Licorera dueña del registro; sostiene el aislamiento entre negocios.', on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='suscripciones.licorera')),
                ('sede', models.ForeignKey(db_column='sede_id', help_text='Sede que recibe la mercancía.', on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='sedes.sede')),
                ('usuario', models.ForeignKey(db_column='usuario_id', help_text='Quién registró la entrada.', on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'entrada de mercancía',
                'verbose_name_plural': 'entradas de mercancía',
                'db_table': 'entrada_mercancia',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LoteInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('compra', 'Compra'), ('traslado', 'Traslado'), ('ajuste_positivo', 'Ajuste positivo')], default='compra', help_text='Cómo nació el lote.', max_length=15)),
                ('cantidad_inicial', models.PositiveIntegerField(help_text='Unidades con las que nació el lote.')),
                ('cantidad_disponible', models.PositiveIntegerField(help_text='Unidades que aún quedan; el PEPS consume primero los más antiguos.')),
                ('costo_unitario', models.DecimalField(decimal_places=2, help_text='Costo de adquisición congelado; no se altera por compras posteriores.', max_digits=12)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, help_text='Define el orden PEPS (primero en entrar, primero en salir).')),
                ('entrada', models.ForeignKey(blank=True, db_column='entrada_id', help_text='Entrada que lo creó (vacío si nació de un ajuste).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.entradamercancia')),
                ('producto', models.ForeignKey(db_column='producto_id', help_text='Referencia a la que pertenece el lote.', on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.producto')),
                ('sede', models.ForeignKey(db_column='sede_id', help_text='Sede donde está físicamente el lote (las existencias son por sede).', on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='sedes.sede')),
            ],
            options={
                'verbose_name': 'lote de inventario',
                'verbose_name_plural': 'lotes de inventario',
                'db_table': 'lote_inventario',
                'ordering': ['fecha_ingreso', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('venta', 'Venta'), ('anulacion_venta', 'Anulación de venta'), ('ajuste_positivo', 'Ajuste positivo'), ('ajuste_negativo', 'Ajuste negativo'), ('traslado_salida', 'Traslado (salida)'), ('traslado_entrada', 'Traslado (entrada)')], help_text='Naturaleza del movimiento.', max_length=16)),
                ('cantidad', models.IntegerField(help_text='Positiva si suma a las existencias, negativa si resta.')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Costo asociado al movimiento, para el kardex valorizado.', max_digits=12, null=True)),
                ('documento_tipo', models.CharField(choices=[('entrada', 'Entrada'), ('venta', 'Venta'), ('traslado', 'Traslado'), ('ajuste', 'Ajuste')], help_text='Tipo del documento que originó el movimiento.', max_length=10)),
                ('documento_id', models.BigIntegerField(help_text='Identificador del documento origen (trazabilidad total).')),
                ('motivo', models.CharField(blank=True, help_text='Obligatorio en los ajustes (RF-INV-06): merma, rotura, conteo…', max_length=255, null=True)),
                ('saldo_resultante', models.PositiveIntegerField(help_text='Existencias del producto en la sede después del movimiento.')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del movimiento.')),
                ('licorera', models.ForeignKey(db_column='licorera_id', help_text='Licorera dueña del registro; sostiene el aislamiento entre negocios.', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='suscripciones.licorera')),
                ('lote', models.ForeignKey(blank=True, db_column='lote_id', help_text='Lote afectado, si aplica.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.loteinventario')),
                ('producto', models.ForeignKey(db_column='producto_id', help_text='Referencia afectada.', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.producto')),
                ('sede', models.ForeignKey(db_column='sede_id', help_text='Sede afectada.', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='sedes.sede')),
                ('usuario', models.ForeignKey(db_column='usuario_id', help_text='Quién causó el movimiento.', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'db_table': 'movimiento_inventario',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
