# Generated by Django 5.2.17 on 2026-10-07 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suscripciones', '0004_alter_suscripcion_fecha_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la sede («Sede principal», «Sucursal Centro»…).', max_length=80)),
                ('direccion', models.CharField(blank=True, help_text='Dirección física.', max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de la sede.', max_length=20, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Baja lógica: una sede cerrada conserva su historial.')),
                ('licorera', models.ForeignKey(db_column='licorera_id', help_text='Licorera dueña del registro; sostiene el aislamiento entre negocios.', on_delete=django.db.models.deletion.PROTECT, related_name='sedes', to='suscripciones.licorera')),
            ],
            options={
                'verbose_name': 'sede',
                'verbose_name_plural': 'sedes',
                'db_table': 'sede',
            },
        ),
    ]
