# Generated by Django 5.2.17 on 2026-09-15 03:43

import django.db.models.deletion
import seguridad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suscripciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(help_text='Qué puede hacer el rol, en lenguaje claro.', max_length=150)),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo', models.EmailField(help_text='Identificador de acceso; único en toda la plataforma.', max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(db_column='contrasena_hash', max_length=255)),
                ('intentos_fallidos', models.PositiveSmallIntegerField(default=0, help_text='Contador para el bloqueo tras cinco intentos (RF-SEG-02).')),
                ('bloqueado_hasta', models.DateTimeField(blank=True, help_text='Fin del bloqueo temporal. Vacío si no está bloqueado.', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Baja lógica: el inactivo no entra, su historial permanece.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='ultimo_acceso', null=True)),
                ('licorera', models.ForeignKey(blank=True, db_column='licorera_id', help_text='Licorera a la que pertenece. Vacío para el personal de INVENTRA.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='suscripciones.licorera')),
                ('rol', models.ForeignKey(db_column='rol_id', help_text='Rol que define sus permisos.', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='seguridad.rol')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuario',
            },
            managers=[
                ('objects', seguridad.models.UsuarioManager()),
            ],
        ),
    ]
