# Generated by Django 5.2.17 on 2026-09-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_datos_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo_verificado',
            field=models.BooleanField(default=False, help_text='Si la persona confirmó su correo abriendo el enlace que se le envió. Una cuenta sin verificar entra al sistema, pero ve un aviso (D-10).'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(help_text='«administrador_licorera», «vendedor» o «administrador_inventra».', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó la cuenta.'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, db_column='ultimo_acceso', help_text='Última vez que la persona entró al sistema.', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(help_text='Nombre de la persona.', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(db_column='contrasena_hash', help_text='Contraseña cifrada con hash adaptativo; nunca en texto plano (RNF-02).', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto.', max_length=20, null=True),
        ),
    ]
