# Generated by Django 5.2.17 on 2026-09-15 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licorera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre comercial del negocio.', max_length=100)),
                ('nit', models.CharField(blank=True, help_text='NIT o cédula del propietario. Único si se registra.', max_length=20, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(help_text='Correo de contacto del negocio.', max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó la cuenta en la plataforma.')),
                ('activo', models.BooleanField(default=True, help_text='Baja lógica: una licorera retirada conserva su historial.')),
            ],
            options={
                'verbose_name': 'licorera',
                'verbose_name_plural': 'licoreras',
                'db_table': 'licorera',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre comercial del plan: Básico o Pro.', max_length=30, unique=True)),
                ('precio_mensual', models.DecimalField(decimal_places=2, help_text='Precio de lista de la suscripción mensual.', max_digits=12)),
                ('maximo_sedes', models.PositiveIntegerField(blank=True, help_text='Límite de sedes. Vacío significa sin límite.', null=True)),
                ('maximo_usuarios', models.PositiveIntegerField(blank=True, help_text='Límite de usuarios. Vacío significa sin límite.', null=True)),
                ('permite_facturacion', models.BooleanField(default=False, help_text='Si el plan habilita la facturación electrónica.')),
                ('permite_reportes_avanzados', models.BooleanField(default=False, help_text='Si el plan habilita rotación y utilidad.')),
                ('activo', models.BooleanField(default=True, help_text='Permite retirar un plan sin borrar su historial.')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'planes',
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('en_mora', 'En mora'), ('suspendida', 'Suspendida'), ('cancelada', 'Cancelada')], default='activa', help_text='Estado actual de la suscripción.', max_length=12)),
                ('fecha_inicio', models.DateField(help_text='Inicio de la vigencia.')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fin de la vigencia. Vacío mientras esté vigente.', null=True)),
                ('precio_pactado', models.DecimalField(decimal_places=2, help_text='Precio congelado al contratar; los aumentos no cambian el histórico.', max_digits=12)),
                ('licorera', models.ForeignKey(db_column='licorera_id', on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='suscripciones.licorera')),
                ('plan', models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='suscripciones.plan')),
            ],
            options={
                'verbose_name': 'suscripción',
                'verbose_name_plural': 'suscripciones',
                'db_table': 'suscripcion',
            },
        ),
    ]
