# Generated by Django 5.2.17 on 2026-09-27 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0002_datos_planes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licorera',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección principal del negocio.', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='licorera',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='estado',
            field=models.CharField(choices=[('en_prueba', 'En prueba'), ('activa', 'Activa'), ('en_mora', 'En mora'), ('suspendida', 'Suspendida'), ('cancelada', 'Cancelada')], default='activa', help_text='Estado actual de la suscripción.', max_length=12),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='licorera',
            field=models.ForeignKey(db_column='licorera_id', help_text='Licorera dueña del registro; sostiene el aislamiento entre negocios.', on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='suscripciones.licorera'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='plan',
            field=models.ForeignKey(db_column='plan_id', help_text='Plan contratado en este período.', on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='suscripciones.plan'),
        ),
    ]
