# Generated by Django 5.2.17 on 2026-10-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0003_alter_licorera_direccion_alter_licorera_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Hasta cuándo vale esta suscripción. La define el Administrador INVENTRA al activar y al renovar, y no puede ser una fecha pasada (RF-SUS-03); al cambiar de plan se acorta al día del cambio.', null=True),
        ),
    ]
